apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.3
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:3.9.0-core
          args:
            - influxdb3
            - serve
            - --node-id
            - influxdb
            - --object-store
            - file
            - --data-dir
            - /var/lib/influxdb3/data
            - --admin-token-file
            - /etc/influxdb3/admin-token/token
          ports:
            - containerPort: 8181
          env:
            - name: INFLUXDB3_LOG_FILTER
              value: info
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb3/data
            - name: influxdb-admin-token
              mountPath: /etc/influxdb3/admin-token
              readOnly: true
      volumes:
        - name: influxdb-data
          emptyDir: {}
        - name: influxdb-admin-token
          secret:
            secretName: influxdb-admin-token
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-admin-token
type: Opaque
stringData:
  token: apiv3_z6XfweFMd3rNML1ixCdvaEkfnQAO-tzC
---
apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-init-k6
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-k6-database
          image: influxdb:3.9.0-core
          command:
            - influxdb3
            - create
            - database
            - k6
          env:
            - name: INFLUXDB3_HOST_URL
              value: http://influxdb:8181
            - name: INFLUXDB3_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-admin-token
                  key: token
