apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: observability
spec:
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP
