apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: compute-resources-area-calidad-dev
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: compute-resources-area-calidad-dev
spec:
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8181
      targetPort: 8181
  type: ClusterIP
